### ISSUE TITLE
Add ability to allocate ancilla qubits within quantum kernels

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/qcor#150]
@tnguyen-ornl will you describe your proposed solution to this in a comment below?

**Comment by tnguyen-ornl** [comment]
I was thinking about having a global auxiliary/ancilla register which we use to allocate temporary qubits inside quantum kernels. The size is dynamic and equal to the maximum number of ancilla qubits in-flight during the whole program.

- Allocate: if there are available qubits in the pool (deallocated from a previous allocation), returns the qubit. Otherwise, increase the size of the buffer to get new qubits.

- Deallocate: return the qubits to the pool. We may just reset the qubit for now, i.e., the user needs to un-compute if need be. 

- Final submission: just grab the global aux. register along with other registers.

The reason that we need to reuse the qubits is that I foresee that these qubits may be used in loops.
This also means that we need to track the lifetime of these ancilla registers, either by an explicit method or some scoping.
