### ISSUE TITLE
qjit kernel name = 't', symbols not found __cxx_global_var_init 

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/qcor#89]
When I try to just in time compile a kernel with name 't' (any function body content), I get a weird symbol not found error coming out of the jit code

```python
def t(q : qreg):
    H(q[0])
    CNOT(q[0], q[1])
    CNOT(q[1], q[2])
    Measure(q[0])
    Measure(q[1])
    Measure(q[2])
```

```bash
Failure value returned from cantFail wrapped call
Symbols not found: [ __cxx_global_var_init ]
UNREACHABLE executed at /usr/local/aideqc/llvm/include/llvm/Support/Error.h:749!
Aborted (core dumped)
```

**Comment by tnguyen-ornl** [comment]
This bug is due to this line https://github.com/ORNL-QCI/qcor/blob/master/runtime/jit/qcor_jit.in.cpp#L566
The matching condition is too broad, hence in this case it matched this symbol `__cxx_global_var_init` (letter t).
In general, this could be quite a serious bug especially if the kernel name is short.
